services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
  