services:
  db:
    ports:
      - "5432:5432"
    container_name: postgresql_container
    image: postgres
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: .
    container_name: identity_provider_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/cloud
      db-username: postgres
      db-password: admin
    depends_on:
      - db

volumes:
  postgres-data: